# nix/init-app.nix — scaffolder for a fresh downstream consumer
# project under `./<NAME>/`.
#
# Surface:
#
#     nix run github:GoodNet-io/goodnet#init-app -- my-thing
#     cd my-thing
#     nix develop          # auto-env (see `dev-shell-app.nix`)
#     cmake --build build  # produced binary in build/
#
# Produces a six-file skeleton that depends on the kernel flake,
# uses the `goodnet_app(...)` CMake helper (under `cmake/goodnet_app
# .cmake`) for the link / include / RPATH boilerplate, and ships a
# `main.cpp` template that opens against `gn::sdk::Core`. The Core
# type is the RAII wrapper a concurrent SDK commit lands at
# `sdk/cpp/core.hpp`; this template includes the header
# unconditionally and assumes a default-constructible `Core` so a
# user who runs `init-app` followed by `cmake --build` after both
# commits land gets a binary that links and runs.
#
# Generated layout under `./<NAME>/`:
#
#     flake.nix          — inputs.goodnet, devShell pulls
#                          `nix develop goodnet#app`
#     CMakeLists.txt     — find_package(GoodNet) + goodnet_app(...)
#     main.cpp           — `gn::sdk::Core core;` sample
#     .envrc             — `use flake` for direnv users
#     .gitignore         — build/, result, .direnv
#     README.md          — three-command setup recap
#
# Templates use placeholder-substitution (`__NAME__`) through
# `sed` after the quoted heredocs land on disk — same pattern as
# `nix/new-plugin.nix`. The four-space indent inside the heredocs
# is stripped at the end so each generated file lands flush-left.

{ pkgs }:

pkgs.writeShellApplication {
  name = "gn-init-app";
  runtimeInputs = [ pkgs.gnused ];
  text = ''
    set -euo pipefail

    if [ $# -ne 1 ]; then
      cat >&2 <<USAGE
    Usage: nix run goodnet#init-app -- <NAME>
      <NAME>: lowercase identifier matching [a-z][a-z0-9_-]*
              (becomes the project directory + cmake target name)
    USAGE
      exit 1
    fi

    name="$1"

    if ! [[ "$name" =~ ^[a-z][a-z0-9_-]*$ ]]; then
      echo "init-app: name '$name' must match [a-z][a-z0-9_-]*" >&2
      echo "  (lowercase ASCII, may contain digits / underscore / dash," >&2
      echo "   must start with a letter)." >&2
      exit 1
    fi

    if [ -e "$name" ]; then
      echo "init-app: ./$name already exists, refusing to clobber." >&2
      echo "  Remove it manually if you really want to regenerate." >&2
      exit 1
    fi

    mkdir -p "$name"

    subst() {
      sed -e "s|__NAME__|$name|g"
    }

    cat <<'FLAKE' | subst > "$name/flake.nix"
    # Downstream GoodNet consumer — generated by `nix run goodnet#init-app`.
    #
    # The kernel flake exposes a ready-made `app` devShell that
    # exports GOODNET_CORE_LIB / GOODNET_PLUGIN_PATH /
    # GOODNET_IDENTITY / GOODNET_MANIFEST plus LD_LIBRARY_PATH so
    # `cmake --build` and the resulting binary both find the
    # kernel + plugins without any per-user wiring.
    {
      description = "__NAME__ — GoodNet downstream consumer.";

      inputs.goodnet.url  = "github:GoodNet-io/goodnet";
      inputs.nixpkgs.follows = "goodnet/nixpkgs";

      outputs = { self, nixpkgs, goodnet }:
        let
          forAllSystems = f:
            nixpkgs.lib.genAttrs
              [ "x86_64-linux" "aarch64-linux" ]
              (system: f system (import nixpkgs { inherit system; }));
        in
        {
          # Re-export the kernel's `app` shell so
          # `nix develop` from this project root drops straight
          # into a configured environment. No package outputs —
          # this is a consumer, not a library.
          devShells = forAllSystems (system: pkgs: {
            default = goodnet.devShells.''${system}.app;
          });
        };
    }
    FLAKE

    cat <<'CMAKE' | subst > "$name/CMakeLists.txt"
    cmake_minimum_required(VERSION 3.22)
    project(__NAME__ LANGUAGES CXX VERSION 0.1.0)

    # find_package(GoodNet) resolves through the kernel's CMake
    # package config (installed into the nix store profile or via
    # `cmake --install`). It surfaces `GoodNet::sdk`,
    # `GoodNet::kernel_shared`, the `add_plugin()` helper, and —
    # via the bundled `goodnet_app.cmake` — the `goodnet_app()`
    # convenience macro used below.
    find_package(GoodNet REQUIRED)

    # `goodnet_app(TARGET sources...)` adds an executable wired to
    # the kernel's link + include + RPATH boilerplate. Anything
    # this project adds on top (extra link libs, options) goes
    # through plain `target_*` calls after the macro returns.
    goodnet_app(__NAME__ main.cpp)
    CMAKE

    cat <<'CPP' | subst > "$name/main.cpp"
    /// @file   main.cpp
    /// @brief  Minimum-viable GoodNet consumer using gn::sdk::Core.
    ///
    /// The Core RAII wrapper (sdk/cpp/core.hpp) owns the kernel
    /// handle through construction + destruction; throwing
    /// constructors propagate plugin-load / config errors as
    /// exceptions instead of the C ABI's return codes. This sample
    /// constructs the default Core, prints the kernel version, and
    /// exits. Replace the body with the actual connect / listen
    /// flow your consumer wants.

    #include <sdk/cpp/core.hpp>
    #include <sdk/core.h>

    #include <cstdio>
    #include <exception>

    int main() {
        try {
            gn::sdk::Core core;
            std::puts("__NAME__: gn::sdk::Core constructed.");
            std::printf("__NAME__: gn_core_version = %s\n",
                        gn_core_version());
            // TODO: open links, register handlers, talk to peers.
            return 0;
        } catch (const std::exception& e) {
            std::fprintf(stderr, "__NAME__: fatal: %s\n", e.what());
            return 1;
        }
    }
    CPP

    cat <<'ENVRC' > "$name/.envrc"
    use flake
    ENVRC

    cat <<'GITIGNORE' > "$name/.gitignore"
    build/
    build-*/
    result
    result-*
    .direnv/
    .envrc.cache
    *.swp
    GITIGNORE

    cat <<'README' | subst > "$name/README.md"
    # __NAME__

    GoodNet downstream consumer. Generated by
    `nix run goodnet#init-app`.

    ## Three-command setup

    ```sh
    nix run goodnet#bootstrap-env   # one-time per-user XDG layout
    nix develop                     # configured shell (auto-env)
    cmake -B build && cmake --build build
    ```

    `bootstrap-env` only needs to run once per user — it materialises
    `~/.local/share/goodnet/{identity,plugins,manifests,config.json}`
    that every downstream consumer reads through the
    `GOODNET_*` env vars the shell exports.

    ## Run

    ```sh
    ./build/__NAME__
    ```

    The binary opens a `gn::sdk::Core` against the bootstrap env's
    identity / manifest / plugin path. Replace `main.cpp`'s body
    with the connect / listen flow your application needs; the
    `gn::sdk` C++ bridges (`connect_to`, `listen_to`,
    `Subscription`) live under `<sdk/cpp/*.hpp>`.

    ## Counter-party for local testing

    ```sh
    nix run goodnet#sample-peer &
    # prints `peer pubkey: <hex>` + listens on tcp://0.0.0.0:9101
    ./build/__NAME__
    ```

    ## Reference

    See `docs/operator/downstream-app-setup.en.md` in the kernel
    repo for the full setup reference (env vars, override knobs,
    troubleshooting).
    README

    # Heredocs above use a four-space indent so the surrounding
    # Nix indented-string keeps a tidy left margin; strip the
    # prefix before declaring success.
    for f in \
      "$name/flake.nix" \
      "$name/CMakeLists.txt" \
      "$name/main.cpp" \
      "$name/README.md"
    do
      sed -i 's/^    //' "$f"
    done

    cat <<DONE
    Created ./$name/ with:
      flake.nix          — depends on github:GoodNet-io/goodnet
      CMakeLists.txt     — find_package(GoodNet) + goodnet_app(...)
      main.cpp           — gn::sdk::Core sample
      .envrc             — direnv auto-shell
      .gitignore
      README.md

    Next:
      cd $name
      nix run goodnet#bootstrap-env   # one-time
      nix develop                     # configured shell
      cmake -B build && cmake --build build
      ./build/$name
    DONE
  '';
}
