// SPDX-License-Identifier: MIT
/// @file   plugins/transports/ipc/plugin_entry.cpp
/// @brief  Plugin entry surface generated by the `TRANSPORT_PLUGIN`
///         macro from `sdk/cpp/transport_plugin.hpp`.

#include "ipc.hpp"

#include <sdk/cpp/transport_plugin.hpp>

TRANSPORT_PLUGIN(::gn::transport::ipc::IpcTransport, "ipc")
