"""Unit tests for tools/livedoc/renderers.py."""

from __future__ import annotations

from livedoc import renderers


# ── ABI renderers ───────────────────────────────────────────────────

_HOST_API_FACTS = {
    "struct": "host_api_s",
    "header": "sdk/host_api.h",
    "named_slots": 3,
    "reserved_slots": 2,
    "families": {
        "Messaging":       ["send", "disconnect"],
        "Registry queries": ["find_conn_by_pk"],
    },
    "slots": [
        {"name": "send", "signature": "int (*)()",
         "file": "sdk/host_api.h", "line": 10, "family": "Messaging",
         "doc": "Send envelope."},
        {"name": "disconnect", "signature": "int (*)()",
         "file": "sdk/host_api.h", "line": 14, "family": "Messaging",
         "doc": "Close."},
        {"name": "find_conn_by_pk", "signature": "int (*)()",
         "file": "sdk/host_api.h", "line": 18,
         "family": "Registry queries", "doc": "Look up."},
    ],
}


def test_host_api_summary_lists_every_family():
    out = renderers.host_api_summary(_HOST_API_FACTS)
    assert "3 named slots" in out
    # Reserved count surfaces as `2` (rendered with backticks).
    assert "`2` reserved" in out
    assert "Messaging" in out
    assert "Registry queries" in out
    assert "`send`" in out


def test_host_api_summary_carries_generated_note():
    assert "generated by tools/livedoc.py" in renderers.host_api_summary(
        _HOST_API_FACTS,
    )


def test_host_api_slots_table_shape():
    out = renderers.host_api_slots(_HOST_API_FACTS)
    assert "| Slot | Signature | Family |" in out
    # Three slot rows.
    rows = [ln for ln in out.splitlines() if ln.startswith("| [")]
    assert len(rows) == 3


def test_vtable_slots_pipe_escape():
    facts = {
        "struct": "x_t", "header": "sdk/x.h",
        "named_slots": 1, "reserved_slots": 0,
        "slots": [{
            "name": "weird", "signature": "int|fn|()",
            "file": "sdk/x.h", "line": 1, "family": "f", "doc": "",
        }],
    }
    out = renderers.vtable_slots(facts)
    # Pipe characters must be escaped or stripped so the GFM table
    # parser doesn't choke.
    bad_row = [ln for ln in out.splitlines()
               if ln.startswith("|") and "weird" in ln][0]
    assert bad_row.count("|") == 4 or "int\\|fn\\|" in bad_row


# ── Roadmap renderer ────────────────────────────────────────────────

def test_roadmap_status_table_badges():
    facts = {"features": [
        {"name": "A", "status": "done", "evidence": "ev1"},
        {"name": "B", "status": "partial", "evidence": "ev2"},
        {"name": "C", "status": "missing", "evidence": "ev3"},
    ]}
    out = renderers.roadmap_status_table(facts)
    assert "✓ done" in out
    assert "🚧 partial" in out
    assert "✗ missing" in out
    # Evidence column populated.
    for ev in ("ev1", "ev2", "ev3"):
        assert ev in out


def test_roadmap_status_table_empty():
    out = renderers.roadmap_status_table({"features": []})
    assert "Feature" in out


# ── Metrics / config / RFC renderers ────────────────────────────────

def test_metrics_catalog_table_renders():
    facts = {"counters": [
        {"name": "drop.x", "family": "drop",
         "kinds": ["emit_counter"],
         "sources": [{"file": "core/x.cpp", "line": 1}]},
    ]}
    out = renderers.metrics_catalog_table(facts)
    assert "`drop.x`" in out
    assert "core/x.cpp" in out


def test_metrics_catalog_table_empty():
    out = renderers.metrics_catalog_table({"counters": []})
    assert "No counters" in out


def test_config_keys_table_groups_by_family():
    facts = {"keys": [
        {"name": "ice.path_mtu", "type": "int64",
         "family": "ice",
         "sources": [{"file": "plugins/links/ice/x.cpp", "line": 1}]},
        {"name": "udp.cap", "type": "int64", "family": "udp",
         "sources": [{"file": "plugins/links/udp/x.cpp", "line": 1}]},
    ]}
    out = renderers.config_keys_table(facts)
    assert "`ice` keys" in out
    assert "`udp` keys" in out


def test_rfc_coverage_table_badge_and_links():
    facts = {"rfcs": [
        {"rfc": 8445, "title": "ICE", "area": "ICE",
         "status": "full", "implementation": "plugins/links/ice"},
    ]}
    out = renderers.rfc_coverage_table(facts)
    assert "datatracker.ietf.org" in out
    assert "✓ full" in out
    assert "[`plugins/links/ice`]" in out


# ── Embed + plugin_page ─────────────────────────────────────────────

def test_embed_diagram_emits_img_ref():
    out = renderers.embed_diagram("kernel_fsm", caption="hi")
    assert "![kernel fsm](../img/kernel_fsm.svg)" in out
    assert "_hi_" in out


def test_plugin_page_links():
    plugin = {
        "name": "tcp", "path": "plugins/links/tcp",
        "notes": "TCP transport.",
        "schemes": ["tcp"], "composer": True,
    }
    out = renderers.plugin_page(plugin, kind="links")
    assert "**Kind:** links" in out
    assert "`gn.link.tcp`" in out
    assert "**URI schemes:** `tcp`" in out
    assert "**Composer surface:** yes" in out


def test_plugin_page_with_test_count_shows_count():
    plugin = {"name": "tcp", "path": "plugins/links/tcp"}
    out = renderers.plugin_page(plugin, kind="links", test_count=42)
    assert "**Tests:** 42 cases" in out


def test_plugin_page_with_zero_test_count():
    plugin = {"name": "x", "path": "plugins/handlers/x"}
    out = renderers.plugin_page(plugin, kind="handlers", test_count=0)
    assert "**Tests:** none" in out


def test_test_inventory_table_renders():
    facts = {
        "total": 100,
        "groups": [
            {"tree": "kernel", "count": 80, "files": 5},
            {"tree": "plugins/links/tcp", "count": 20, "files": 2},
        ],
    }
    out = renderers.test_inventory_table(facts)
    assert "100 test cases across 2 tree(s)" in out
    # Kernel group hyperlinks to tests/.
    assert "[`tests/`](../../tests)" in out
    assert "plugins/links/tcp" in out
    # Per-row case counts in the cells.
    assert "| 80 |" in out
    assert "| 20 |" in out


def test_test_inventory_table_empty():
    out = renderers.test_inventory_table({"groups": []})
    assert "No test trees" in out
