// SPDX-License-Identifier: Apache-2.0
/// @file   plugins/transports/ws/plugin_entry.cpp
/// @brief  Plugin entry surface generated by the `TRANSPORT_PLUGIN`
///         macro from `sdk/cpp/transport_plugin.hpp`.

#include "ws.hpp"

#include <sdk/cpp/transport_plugin.hpp>

TRANSPORT_PLUGIN(::gn::transport::ws::WsTransport, "ws")
