#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
#
# Peer entrypoint. Two responsibilities:
#
# 1. Materialise the per-peer kernel config from environment vars
#    handed in by docker-compose (PEER_NAME, STUN_URI, TURN_URI,
#    WAIT_FOR_PEER, SIGNAL_DIR, plus optional knobs for rc5
#    scenarios). Generated by direct shell-variable substitution
#    via a heredoc — the `goodnet:nix-static` base image only ships
#    coreutils, no `sed`/`grep`/`envsubst`, so the templating must
#    work with `sh` builtins alone.
# 2. Hand control to /usr/local/bin/peer-harness, which drives the
#    cluster-side ICE connect dance:
#    * publish our pubkey to the shared signal dir
#    * wait for the peer's pubkey
#    * trigger an ICE connect to it
#    * on first inbound byte, write `${SIGNAL_DIR}/${PEER_NAME}.done`
#
# Exits 0 on success, non-zero on timeout / hard failure. The
# scenario test scripts in `run_all.sh` assert on the `.done` /
# `.fail` markers in the shared volume.

set -eu

# Coordinator container has no peer counterpart to ICE-connect to;
# it stays up only to satisfy the compose `depends_on` ordering and
# expose the shared signal volume to the orchestrator. Short-circuit
# before the PEER_NAME / config-template steps run.
if [ "${ROLE:-peer}" = "coordinator" ]; then
    echo "[coordinator] role=coordinator — idling"
    exec sleep infinity
fi

: "${PEER_NAME:?PEER_NAME unset}"
: "${SIGNAL_DIR:=/var/lib/ice3-signal}"
: "${STUN_URI:=stun://10.10.0.10:3478}"
: "${TURN_URI:=turn://goodnet:bench-only-credentials@10.10.0.11:3478}"
: "${WAIT_FOR_PEER:=B}"

# Replace the docker-bridge default route with one that points at
# the per-LAN NAT container. docker's IPAM places the bridge
# gateway at .254 of each subnet (see docker-compose.yml's `ipam`
# block); the NAT container takes .1 and is the only route to the
# `net` subnet (10.10.0.0/24) where STUN + TURN live. The PATH
# the route uses comes from PEER_NAME — A → 10.20.0.1, B →
# 10.30.0.1. busybox `ip` from /usr/local/bin/ip handles the
# netlink talk; the goodnet base image ships only coreutils.
case "${PEER_NAME}" in
    A) nat_gateway="10.20.0.1" ;;
    B) nat_gateway="10.30.0.1" ;;
    *) nat_gateway="" ;;
esac
if [ -n "${nat_gateway}" ] && [ -x /usr/local/bin/ip ]; then
    echo "[peer-${PEER_NAME}] swapping default route → ${nat_gateway}"
    /usr/local/bin/ip route del default 2>/dev/null || true
    /usr/local/bin/ip route add default via "${nat_gateway}" 2>&1 \
        || echo "[peer-${PEER_NAME}] WARN: failed to install default route"
    /usr/local/bin/ip route show
fi

: "${STUN_URI_EXTRA:=}"
: "${TURN_URI_EXTRA:=}"

# rc5 ICE knobs — every scenario picks safe defaults so the
# existing fixtures don't have to know about them. The schema
# treats missing keys as defaults too, but emitting them with
# explicit values keeps the rendered config diffable.
: "${TURN_BACKUP_INTERVAL_S:=5}"
: "${ICE_LITE_MODE:=false}"
: "${ICE_MDNS_OBFUSCATE:=false}"
: "${ICE_ENABLE_IPV6:=false}"
: "${ICE_PMTU_ACTIVE_PROBING:=false}"
: "${ICE_PORT_PREDICTION_STRIDE_MAX:=0}"
: "${ICE_TCP_TLS_ONLY:=false}"
: "${ICE_SESSION_TIMEOUT_S:=10}"
: "${TURN_USER:=goodnet}"
: "${TURN_PASS:=bench-only-credentials}"

# QUIC-over-ICE knob. When true, load gn.link.quic alongside
# gn.link.ice and switch the default connect scheme to
# `quic://<peer-pk>` — the 64-hex peer-pk in the URI triggers
# carrier=ice routing inside the QUIC composer, so the handshake
# rides the UDP socket ICE nominated rather than opening a fresh
# one.
: "${QUIC_OVER_ICE:=false}"
if [ "${QUIC_OVER_ICE}" = "true" ]; then
    QUIC_PLUGIN_ENTRY=', { "name": "goodnet_link_quic", "path": "/plugins/libgoodnet_link_quic.so" }'
    CONNECT_SCHEME="quic"
else
    QUIC_PLUGIN_ENTRY=""
    CONNECT_SCHEME="udp"
fi

mkdir -p "${SIGNAL_DIR}" /etc/goodnet /var/lib/goodnet

# Build a JSON-array body for the stun/turn server lists by
# concatenating the primary URI with anything in STUN_URI_EXTRA /
# TURN_URI_EXTRA (comma-separated, ASCII).
join_uris() {
    primary="$1"
    extras="$2"
    out="\"${primary}\""
    if [ -n "${extras}" ]; then
        IFS=','
        for u in ${extras}; do
            # Trim surrounding spaces. `${u# }` / `${u% }` strip a
            # single leading/trailing blank — good enough for the
            # comma-separated list shape the orchestrator emits.
            while [ "${u#" "}" != "${u}" ]; do u="${u#" "}"; done
            while [ "${u%" "}" != "${u}" ]; do u="${u%" "}"; done
            [ -z "${u}" ] && continue
            out="${out}, \"${u}\""
        done
        unset IFS
    fi
    printf '%s' "${out}"
}

STUN_SERVERS_JSON="$(join_uris "${STUN_URI}" "${STUN_URI_EXTRA}")"
TURN_SERVERS_JSON="$(join_uris "${TURN_URI}" "${TURN_URI_EXTRA}")"

# Materialise the per-peer config via a heredoc. Shell variable
# expansion inside an unquoted-marker heredoc handles every
# substitution without invoking `sed`. Field names mirror the
# config schema documented in `core/config/config.cpp`.
cat > /etc/goodnet/peer.json <<EOF
{
  "kernel": {
    "node_id": "${PEER_NAME}",
    "identity_path": "/var/lib/goodnet/identity-${PEER_NAME}.bin"
  },
  "log": {
    "level": "${ICE3_LOG_LEVEL:-info}",
    "console_level": "${ICE3_LOG_LEVEL:-info}"
  },
  "plugins": [
    { "name": "goodnet_security_null",     "path": "/plugins/libgoodnet_security_null.so"     },
    { "name": "goodnet_security_noise",    "path": "/plugins/libgoodnet_security_noise.so"    },
    { "name": "goodnet_link_udp",          "path": "/plugins/libgoodnet_link_udp.so"          },
    { "name": "goodnet_link_tcp",          "path": "/plugins/libgoodnet_link_tcp.so"          },
    { "name": "goodnet_link_ice",          "path": "/plugins/libgoodnet_link_ice.so"          }${QUIC_PLUGIN_ENTRY},
    { "name": "goodnet_handler_heartbeat", "path": "/plugins/libgoodnet_handler_heartbeat.so" }
  ],
  "ice": {
    "stun_servers": [ ${STUN_SERVERS_JSON} ],
    "turn_servers": [ ${TURN_SERVERS_JSON} ],
    "turn_username": "${TURN_USER}",
    "turn_password": "${TURN_PASS}",
    "session_timeout_s": ${ICE_SESSION_TIMEOUT_S:-30},
    "keepalive_interval_s": 10,
    "consent_max_failures": 3,
    "consent_max_recovery": 3,
    "turn_backup_interval_s": ${TURN_BACKUP_INTERVAL_S},
    "lite_mode": ${ICE_LITE_MODE},
    "mdns_obfuscate_host_candidates": ${ICE_MDNS_OBFUSCATE},
    "enable_ipv6": ${ICE_ENABLE_IPV6},
    "pmtud_active_probing": ${ICE_PMTU_ACTIVE_PROBING},
    "port_prediction_stride_max": ${ICE_PORT_PREDICTION_STRIDE_MAX},
    "tcp_tls_only": ${ICE_TCP_TLS_ONLY}
  },
  "signal": {
    "shared_dir": "${SIGNAL_DIR}",
    "self": "${PEER_NAME}",
    "peer": "${WAIT_FOR_PEER}"
  },
  "connect": {
    "scheme": "${CONNECT_SCHEME}"
  }
}
EOF

echo "[peer-${PEER_NAME}] config:"
cat /etc/goodnet/peer.json

# Hand control to the harness binary built on the host and copied
# into the image. The harness reads PEER_NAME / WAIT_FOR_PEER /
# SIGNAL_DIR / CONFIG / PLUGINS_DIR / QUIC_OVER_ICE / HARNESS_TIMEOUT_S
# from the environment, publishes our pubkey into the shared
# signal volume, polls for the peer's pubkey, drives the ICE
# connect, and writes the `${PEER_NAME}.done` marker on first
# inbound byte. On hard failure (config / plugin / connect) the
# harness writes `${PEER_NAME}.fail` before exiting non-zero.
export PEER_NAME
export WAIT_FOR_PEER
export SIGNAL_DIR
export CONFIG=/etc/goodnet/peer.json
export PLUGINS_DIR=/plugins
export QUIC_OVER_ICE
: "${HARNESS_TIMEOUT_S:=30}"
export HARNESS_TIMEOUT_S

echo "[peer-${PEER_NAME}] starting peer-harness"
exec /usr/local/bin/peer-harness
