"""Markdown renderers — fact-dict → markdown body.

Each renderer takes a parsed fact-dict (the YAML loaded from
`docs/_facts/<name>.yaml`) and returns the markdown body that goes
between the `<!-- livedoc:NAME -->` markers in a hand-written doc.

The output is GitHub-flavored markdown — tables, code-fences,
emoji status badges. Generated content never wraps free prose;
that stays the author's job. Renderers only emit factual extracts
that drift quickly (slot lists, status tables, plugin inventories).

The auto-generated body always opens with `<!-- generated by
tools/livedoc.py — do not edit by hand -->` so a reader who sees
the file in a code review knows they should not be patching the
content directly.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Iterable


GENERATED_NOTE = (
    "<!-- generated by tools/livedoc.py — do not edit by hand; "
    "rerun `make livedoc` to refresh -->"
)


def _file_link(slot: dict) -> str:
    """Hyperlink slot.name → `sdk/host_api.h#L75` for GitHub render."""
    return f"[{slot['name']}](../../{slot['file']}#L{slot['line']})"


def _code(s: str) -> str:
    return f"`{s}`"


# ── ABI vtable renderers ────────────────────────────────────────────

def host_api_summary(facts: dict) -> str:
    """One-line summary plus family-bullet list."""
    families = facts.get("families", {})
    n_slots = facts.get("named_slots", 0)
    n_res = facts.get("reserved_slots", 0)
    header = facts.get("header", "sdk/host_api.h")
    lines = [
        GENERATED_NOTE,
        "",
        f"`host_api_t` exposes **{n_slots} named slots** plus "
        f"`{n_res}` reserved pointers for forward-compatible growth, "
        f"declared in [`{header}`](../../{header}).",
        "",
        "Slots are grouped by purpose:",
        "",
    ]
    for fam in sorted(families):
        slots = families[fam]
        joined = ", ".join(_code(s) for s in slots)
        lines.append(f"- **{fam}** — {joined}")
    return "\n".join(lines)


def host_api_slots(facts: dict) -> str:
    """Full slot table — name, signature, family, source ref."""
    slots = facts.get("slots", [])
    lines = [
        GENERATED_NOTE,
        "",
        "| Slot | Signature | Family |",
        "|---|---|---|",
    ]
    for s in slots:
        sig = s["signature"].replace("|", "\\|")
        fam = s["family"].split("(")[0].strip()
        lines.append(
            f"| {_file_link(s)} | `{sig}` | {fam} |"
        )
    return "\n".join(lines)


def vtable_slots(facts: dict, *, title: str | None = None) -> str:
    """Generic table renderer for any vtable fact-dict."""
    struct = facts.get("struct", "?")
    n_slots = facts.get("named_slots", 0)
    n_res = facts.get("reserved_slots", 0)
    header = facts.get("header", "")
    head = title or f"`{struct}`"
    lines = [
        GENERATED_NOTE,
        "",
        f"{head} — **{n_slots} slots** + `{n_res}` reserved "
        f"([`{header}`](../../{header})).",
        "",
        "| Slot | Signature |",
        "|---|---|",
    ]
    for s in facts.get("slots", []):
        sig = s["signature"].replace("|", "\\|")
        lines.append(f"| {_file_link(s)} | `{sig}` |")
    return "\n".join(lines)


# ── Roadmap renderer ────────────────────────────────────────────────

_STATUS_BADGE = {
    "done":    "✓ done",
    "partial": "🚧 partial",
    "missing": "✗ missing",
}


def roadmap_status_table(status: dict) -> str:
    """Status-tagged table of every roadmap bullet."""
    rows = status.get("features", [])
    lines = [
        GENERATED_NOTE,
        "",
        "| Feature | Status | Evidence |",
        "|---|---|---|",
    ]
    for f in rows:
        name = f.get("name", "?")
        badge = _STATUS_BADGE.get(f.get("status", "missing"), "—")
        ev = (f.get("evidence", "") or "").replace("|", "\\|")
        lines.append(f"| {name} | {badge} | {ev} |")
    return "\n".join(lines)


# ── Plugin / extension inventories ──────────────────────────────────

def link_carriers_list(plugins: list[dict]) -> str:
    """List of link plugins discovered in the plugin tree."""
    lines = [
        GENERATED_NOTE,
        "",
        "| Plugin | Scheme | Tree | Composer | Notes |",
        "|---|---|---|---|---|",
    ]
    for p in plugins:
        name = p.get("name", "?")
        scheme = ", ".join(_code(s) for s in p.get("schemes", [])) or "—"
        tree = f"[`{p['path']}`](../../{p['path']})"
        composer = "yes" if p.get("composer") else "no"
        notes = p.get("notes", "")
        lines.append(f"| {name} | {scheme} | {tree} | {composer} | {notes} |")
    return "\n".join(lines)


def plugin_inventory(inv: dict) -> str:
    """Cross-family plugin inventory grouped by kind."""
    lines = [GENERATED_NOTE, ""]
    for kind in sorted(inv):
        entries = inv[kind]
        if not entries:
            continue
        lines.append(f"### {kind.capitalize()} plugins")
        lines.append("")
        lines.append("| Name | Path | Notes |")
        lines.append("|---|---|---|")
        for e in entries:
            path = e.get("path", "?")
            link = f"[`{path}`](../../{path})"
            notes = e.get("notes", "")
            lines.append(f"| {e['name']} | {link} | {notes} |")
        lines.append("")
    return "\n".join(lines).rstrip()


def extension_surface(facts: dict) -> str:
    """Composer / extension vtable surface table."""
    return vtable_slots(facts, title="Link extension surface")


# ── ABI size summary ────────────────────────────────────────────────

def abi_size(facts: dict) -> str:
    """One-line struct sizing note (slots + reserved)."""
    struct = facts.get("struct", "?")
    n_slots = facts.get("named_slots", 0)
    n_res = facts.get("reserved_slots", 0)
    return (
        f"{GENERATED_NOTE}\n\n"
        f"`{struct}` — **{n_slots} named slots** + `{n_res}` reserved."
    )


# ── Metrics + config catalogs ───────────────────────────────────────

def metrics_catalog_table(facts: dict) -> str:
    """Table of counters discovered by emit_counter grep."""
    rows = facts.get("counters") or []
    if not rows:
        return f"{GENERATED_NOTE}\n\n_No counters discovered._"
    lines = [GENERATED_NOTE, ""]
    lines.append(f"_{len(rows)} counter name(s) emitted across the tree._")
    lines.append("")
    lines.append("| Counter | Family | Emitted from |")
    lines.append("|---|---|---|")
    for c in rows:
        srcs = c.get("sources", [])
        # Collapse to unique file paths to keep the cell readable.
        files = sorted({s["file"] for s in srcs})
        cells = ", ".join(
            f"[`{f}`](../../{f})" for f in files[:4]
        )
        if len(files) > 4:
            cells += f" + {len(files) - 4} more"
        lines.append(f"| `{c['name']}` | {c['family']} | {cells} |")
    return "\n".join(lines)


def config_keys_table(facts: dict) -> str:
    """Table of config keys read via gn_config_get_*."""
    rows = facts.get("keys") or []
    if not rows:
        return f"{GENERATED_NOTE}\n\n_No config keys discovered._"
    by_family: dict[str, list[dict]] = {}
    for k in rows:
        by_family.setdefault(k.get("family", "misc"), []).append(k)
    lines = [GENERATED_NOTE, ""]
    lines.append(f"_{len(rows)} config key(s) read by core / plugins, "
                 f"grouped by family._")
    lines.append("")
    for fam in sorted(by_family):
        lines.append(f"### `{fam}` keys")
        lines.append("")
        lines.append("| Key | Type | Reader |")
        lines.append("|---|---|---|")
        for k in by_family[fam]:
            first = (k.get("sources") or [{}])[0]
            f = first.get("file", "")
            line = first.get("line", "")
            anchor = f"[`{f}#L{line}`](../../{f}#L{line})" if f else "—"
            lines.append(f"| `{k['name']}` | `{k['type']}` | {anchor} |")
        lines.append("")
    return "\n".join(lines).rstrip()


# ── RFC coverage ────────────────────────────────────────────────────

_RFC_STATUS_BADGE = {
    "full":     "✓ full",
    "partial":  "🚧 partial",
    "planned":  "○ planned",
    "out":      "— out of scope",
}


def rfc_coverage_table(facts: dict) -> str:
    """Hand-curated RFC implementation map."""
    rows = facts.get("rfcs") or []
    if not rows:
        return f"{GENERATED_NOTE}\n\n_No RFC coverage entries._"
    by_area: dict[str, list[dict]] = {}
    for r in rows:
        by_area.setdefault(r.get("area", "misc"), []).append(r)
    lines = [GENERATED_NOTE, ""]
    for area in sorted(by_area):
        lines.append(f"### {area}")
        lines.append("")
        lines.append("| RFC | Title | Status | Implementation |")
        lines.append("|---|---|---|---|")
        for r in by_area[area]:
            badge = _RFC_STATUS_BADGE.get(r.get("status", "planned"), "—")
            impl = r.get("implementation", "")
            if impl.startswith("plugins/") or impl.startswith("core/"):
                impl_md = f"[`{impl}`](../../{impl})"
            else:
                impl_md = impl
            lines.append(
                f"| [RFC {r['rfc']}]"
                f"(https://datatracker.ietf.org/doc/html/rfc{r['rfc']}) "
                f"| {r.get('title','—')} | {badge} | {impl_md} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip()


# ── Diagram embedder ────────────────────────────────────────────────

def embed_diagram(name: str, *, caption: str | None = None,
                  alt: str | None = None) -> str:
    """Embed an SVG from docs/img/<name>.svg by markdown image ref.

    The caption renders as an italic line beneath the image so a
    reader scanning the doc gets a one-line synopsis without
    clicking through to the SVG.
    """
    img_alt = alt or name.replace("_", " ")
    body = [
        GENERATED_NOTE,
        "",
        f"![{img_alt}](../img/{name}.svg)",
    ]
    if caption:
        body.append("")
        body.append(f"_{caption}_")
    return "\n".join(body)


# ── Test inventory ──────────────────────────────────────────────────

def test_inventory_table(facts: dict) -> str:
    """Per-tree table of gtest / rapidcheck case counts."""
    groups = facts.get("groups") or []
    if not groups:
        return f"{GENERATED_NOTE}\n\n_No test trees discovered._"
    total = facts.get("total", sum(g.get("count", 0) for g in groups))
    lines = [
        GENERATED_NOTE,
        "",
        f"_{total} test cases across {len(groups)} tree(s)._",
        "",
        "| Tree | Cases | Files |",
        "|---|---:|---:|",
    ]
    for g in groups:
        tree = g.get("tree", "?")
        if tree.startswith("plugins/"):
            link = f"[`{tree}`](../../{tree})"
        elif tree == "kernel":
            link = "[`tests/`](../../tests)"
        else:
            link = f"`{tree}`"
        lines.append(
            f"| {link} | {g.get('count', 0)} | {g.get('files', 0)} |"
        )
    return "\n".join(lines)


# ── Per-plugin page renderer ────────────────────────────────────────

def plugin_page(plugin: dict, *, kind: str,
                test_count: int | None = None) -> str:
    """Render a single plugin's auto-page from an inventory entry.

    If `test_count` is supplied, an extra **Tests:** line surfaces
    the count from `docs/_facts/test_inventory.yaml`.
    """
    name = plugin.get("name", "?")
    path = plugin.get("path", "?")
    notes = plugin.get("notes", "")
    lines = [
        GENERATED_NOTE,
        "",
        f"**Kind:** {kind}",
        f"**Source tree:** [`{path}`](../../{path})",
        f"**Slot:** `gn.link.{name}`" if kind == "links"
        else f"**Slot:** `{name}`",
    ]
    if kind == "links":
        schemes = plugin.get("schemes") or []
        if schemes:
            lines.append("**URI schemes:** "
                         + ", ".join(f"`{s}`" for s in schemes))
        composer = "yes" if plugin.get("composer") else "no"
        lines.append(f"**Composer surface:** {composer}")
    if test_count is not None:
        if test_count > 0:
            lines.append(
                f"**Tests:** {test_count} cases in "
                f"[`{path}/tests`](../../{path}/tests)"
            )
        else:
            lines.append("**Tests:** none in plugin tree")
    lines.append("")
    if notes:
        lines.append(f"_{notes}_")
        lines.append("")
    lines.append("## Source")
    lines.append("")
    lines.append(f"This page summarises [`{path}/README.md`](../../{path}/README.md). "
                 f"For build instructions, configure flags, and contract details "
                 f"open the plugin's own README directly.")
    return "\n".join(lines)

