"""Markdown renderers — fact-dict → markdown body.

Each renderer takes a parsed fact-dict (the YAML loaded from
`docs/_facts/<name>.yaml`) and returns the markdown body that goes
between the `<!-- livedoc:NAME -->` markers in a hand-written doc.

The output is GitHub-flavored markdown — tables, code-fences,
emoji status badges. Generated content never wraps free prose;
that stays the author's job. Renderers only emit factual extracts
that drift quickly (slot lists, status tables, plugin inventories).

The auto-generated body always opens with `<!-- generated by
tools/livedoc.py — do not edit by hand -->` so a reader who sees
the file in a code review knows they should not be patching the
content directly.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Iterable


GENERATED_NOTE = (
    "<!-- generated by tools/livedoc.py — do not edit by hand; "
    "rerun `make livedoc` to refresh -->"
)


def _file_link(slot: dict) -> str:
    """Hyperlink slot.name → `sdk/host_api.h#L75` for GitHub render."""
    return f"[{slot['name']}](../../{slot['file']}#L{slot['line']})"


def _code(s: str) -> str:
    return f"`{s}`"


# ── ABI vtable renderers ────────────────────────────────────────────

def host_api_summary(facts: dict) -> str:
    """One-line summary plus family-bullet list."""
    families = facts.get("families", {})
    n_slots = facts.get("named_slots", 0)
    n_res = facts.get("reserved_slots", 0)
    header = facts.get("header", "sdk/host_api.h")
    lines = [
        GENERATED_NOTE,
        "",
        f"`host_api_t` exposes **{n_slots} named slots** plus "
        f"`{n_res}` reserved pointers for forward-compatible growth, "
        f"declared in [`{header}`](../../{header}).",
        "",
        "Slots are grouped by purpose:",
        "",
    ]
    for fam in sorted(families):
        slots = families[fam]
        joined = ", ".join(_code(s) for s in slots)
        lines.append(f"- **{fam}** — {joined}")
    return "\n".join(lines)


def host_api_slots(facts: dict) -> str:
    """Full slot table — name, signature, family, source ref."""
    slots = facts.get("slots", [])
    lines = [
        GENERATED_NOTE,
        "",
        "| Slot | Signature | Family |",
        "|---|---|---|",
    ]
    for s in slots:
        sig = s["signature"].replace("|", "\\|")
        fam = s["family"].split("(")[0].strip()
        lines.append(
            f"| {_file_link(s)} | `{sig}` | {fam} |"
        )
    return "\n".join(lines)


def vtable_slots(facts: dict, *, title: str | None = None) -> str:
    """Generic table renderer for any vtable fact-dict."""
    struct = facts.get("struct", "?")
    n_slots = facts.get("named_slots", 0)
    n_res = facts.get("reserved_slots", 0)
    header = facts.get("header", "")
    head = title or f"`{struct}`"
    lines = [
        GENERATED_NOTE,
        "",
        f"{head} — **{n_slots} slots** + `{n_res}` reserved "
        f"([`{header}`](../../{header})).",
        "",
        "| Slot | Signature |",
        "|---|---|",
    ]
    for s in facts.get("slots", []):
        sig = s["signature"].replace("|", "\\|")
        lines.append(f"| {_file_link(s)} | `{sig}` |")
    return "\n".join(lines)


# ── Roadmap renderer ────────────────────────────────────────────────

_STATUS_BADGE = {
    "done":    "✓ done",
    "partial": "🚧 partial",
    "missing": "✗ missing",
}


def roadmap_status_table(status: dict) -> str:
    """Status-tagged table of every roadmap bullet."""
    rows = status.get("features", [])
    lines = [
        GENERATED_NOTE,
        "",
        "| Feature | Status | Evidence |",
        "|---|---|---|",
    ]
    for f in rows:
        name = f.get("name", "?")
        badge = _STATUS_BADGE.get(f.get("status", "missing"), "—")
        ev = (f.get("evidence", "") or "").replace("|", "\\|")
        lines.append(f"| {name} | {badge} | {ev} |")
    return "\n".join(lines)


# ── Plugin / extension inventories ──────────────────────────────────

def link_carriers_list(plugins: list[dict]) -> str:
    """List of link plugins discovered in the plugin tree."""
    lines = [
        GENERATED_NOTE,
        "",
        "| Plugin | Scheme | Tree | Composer | Notes |",
        "|---|---|---|---|---|",
    ]
    for p in plugins:
        name = p.get("name", "?")
        scheme = ", ".join(_code(s) for s in p.get("schemes", [])) or "—"
        tree = f"[`{p['path']}`](../../{p['path']})"
        composer = "yes" if p.get("composer") else "no"
        notes = p.get("notes", "")
        lines.append(f"| {name} | {scheme} | {tree} | {composer} | {notes} |")
    return "\n".join(lines)


def plugin_inventory(inv: dict) -> str:
    """Cross-family plugin inventory grouped by kind."""
    lines = [GENERATED_NOTE, ""]
    for kind in sorted(inv):
        entries = inv[kind]
        if not entries:
            continue
        lines.append(f"### {kind.capitalize()} plugins")
        lines.append("")
        lines.append("| Name | Path | Notes |")
        lines.append("|---|---|---|")
        for e in entries:
            path = e.get("path", "?")
            link = f"[`{path}`](../../{path})"
            notes = e.get("notes", "")
            lines.append(f"| {e['name']} | {link} | {notes} |")
        lines.append("")
    return "\n".join(lines).rstrip()


def extension_surface(facts: dict) -> str:
    """Composer / extension vtable surface table."""
    return vtable_slots(facts, title="Link extension surface")


# ── ABI size summary ────────────────────────────────────────────────

def abi_size(facts: dict) -> str:
    """One-line struct sizing note (slots + reserved)."""
    struct = facts.get("struct", "?")
    n_slots = facts.get("named_slots", 0)
    n_res = facts.get("reserved_slots", 0)
    return (
        f"{GENERATED_NOTE}\n\n"
        f"`{struct}` — **{n_slots} named slots** + `{n_res}` reserved."
    )
