// SPDX-License-Identifier: MIT
/// @file   plugins/transports/udp/plugin_entry.cpp
/// @brief  Plugin entry surface generated by the `TRANSPORT_PLUGIN`
///         macro from `sdk/cpp/transport_plugin.hpp`.
///
/// The macro emits the five `gn_plugin_*` exports, the kernel-facing
/// `gn_transport_vtable_t`, the `gn.transport.udp` extension vtable,
/// and the descriptor table. The implementation class
/// (`UdpTransport`) supplies the byte-moving logic and the static
/// capability descriptor; everything else is boilerplate the macro
/// owns.

#include "udp.hpp"

#include <sdk/cpp/transport_plugin.hpp>

TRANSPORT_PLUGIN(::gn::transport::udp::UdpTransport, "udp")
