// SPDX-License-Identifier: Apache-2.0
/// @file   plugins/links/ws/plugin_entry.cpp
/// @brief  Plugin entry surface generated by the `LINK_PLUGIN`
///         macro from `sdk/cpp/transport_plugin.hpp`.

#include "ws.hpp"

#include <sdk/cpp/link_plugin.hpp>

LINK_PLUGIN(::gn::link::ws::WsLink, "ws")
