// SPDX-License-Identifier: MIT
/// @file   plugins/links/tcp/plugin_entry.cpp
/// @brief  Plugin entry surface generated by the `LINK_PLUGIN`
///         macro from `sdk/cpp/transport_plugin.hpp`.

#include "tcp.hpp"

#include <sdk/cpp/link_plugin.hpp>

LINK_PLUGIN(::gn::link::tcp::TcpLink, "tcp")
