// SPDX-License-Identifier: MIT
/// @file   plugins/links/ipc/plugin_entry.cpp
/// @brief  Plugin entry surface generated by the `GN_LINK_PLUGIN`
///         macro from `sdk/cpp/link_plugin.hpp`.

#include "ipc.hpp"

#include <sdk/cpp/link_plugin.hpp>

GN_LINK_PLUGIN(::gn::link::ipc::IpcLink, "ipc")
