// SPDX-License-Identifier: Apache-2.0
/// @file   plugins/transports/tls/plugin_entry.cpp
/// @brief  Plugin entry surface generated by the `TRANSPORT_PLUGIN`
///         macro from `sdk/cpp/transport_plugin.hpp`.

#include "tls.hpp"

#include <sdk/cpp/transport_plugin.hpp>

TRANSPORT_PLUGIN(::gn::transport::tls::TlsTransport, "tls")
