// SPDX-License-Identifier: MIT
/// @file   plugins/transports/tcp/plugin_entry.cpp
/// @brief  Plugin entry surface generated by the `TRANSPORT_PLUGIN`
///         macro from `sdk/cpp/transport_plugin.hpp`.

#include "tcp.hpp"

#include <sdk/cpp/transport_plugin.hpp>

TRANSPORT_PLUGIN(::gn::transport::tcp::TcpTransport, "tcp")
